// This file is auto-generated by TanStack Router

import { FileRoute, lazyRouteComponent } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'

// Create Virtual Routes

const CartComponentImport = new FileRoute('/cart').createRoute()
const IndexComponentImport = new FileRoute('/').createRoute()
const ProductsProductIdComponentImport = new FileRoute(
  '/products/$productId',
).createRoute()

// Create/Update Routes

const CartComponentRoute = CartComponentImport.update({
  path: '/cart',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/cart.component'),
    'component',
  ),
})

const IndexComponentRoute = IndexComponentImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).update({
  component: lazyRouteComponent(
    () => import('./routes/index.component'),
    'component',
  ),
})

const ProductsProductIdComponentRoute = ProductsProductIdComponentImport.update(
  {
    path: '/products/$productId',
    getParentRoute: () => rootRoute,
  } as any,
).update({
  component: lazyRouteComponent(
    () => import('./routes/products/$productId.component'),
    'component',
  ),
})

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexComponentImport
      parentRoute: typeof rootRoute
    }
    '/cart': {
      preLoaderRoute: typeof CartComponentImport
      parentRoute: typeof rootRoute
    }
    '/products/$productId': {
      preLoaderRoute: typeof ProductsProductIdComponentImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexComponentRoute,
  CartComponentRoute,
  ProductsProductIdComponentRoute,
])
